# Generated by Django 5.2.5 on 2025-08-12 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=10)),
                ('birth_year', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dorm_type', models.CharField(max_length=10)),
                ('intro_sentence', models.CharField(max_length=10)),
                ('daily_rhythm', models.CharField(max_length=20)),
                ('wake_habit', models.CharField(max_length=20)),
                ('weekend_life', models.CharField(max_length=20)),
                ('sleep_habit', models.CharField(max_length=20)),
                ('personality_type', models.CharField(max_length=20)),
                ('opinion_style', models.CharField(max_length=20)),
                ('privacy_need', models.CharField(max_length=20)),
                ('scent_sensitivity', models.CharField(max_length=20)),
                ('earphone_use', models.CharField(max_length=20)),
                ('preferred_temp', models.CharField(max_length=20)),
                ('cleaning_style', models.CharField(max_length=20)),
                ('study_place', models.CharField(max_length=20)),
                ('furniture_sharing', models.CharField(max_length=20)),
                ('shared_item_opinion', models.CharField(max_length=20)),
                ('outing_frequency', models.CharField(max_length=20)),
                ('smoking', models.CharField(max_length=20)),
                ('military', models.CharField(blank=True, max_length=20)),
                ('profile_emoji', models.CharField(blank=True, default='', max_length=4)),
                ('keyword_tags', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
