# Generated by Django 5.2.5 on 2025-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateit', '0002_customuser_student_id_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
