# Generated by Django 5.2.5 on 2025-08-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateit', '0003_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='furniture_sharing',
            new_name='shower_time',
        ),
    ]
