# Generated by Django 5.2.5 on 2025-08-26 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateit', '0004_rename_furniture_sharing_userprofile_shower_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmed_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_partner_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
