# Generated by Django 5.2.5 on 2025-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateit', '0005_userprofile_confirmed_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancel_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
