# Generated by Django 5.2.5 on 2025-08-27 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateit', '0006_userprofile_cancel_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_roommate_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_roommate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sender', 'receiver', 'status'], name='yeon_roomma_sender__4e75ef_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'P')), fields=('sender', 'receiver', 'status'), name='uniq_pending_roommate_request_pair')],
            },
        ),
    ]
